### ISSUE TITLE
Not working when using diffirent networks

### ISSUE THREAD

**Issue by vforv** [Basscord/webrtc-video-broadcast#2]
Hello

I tested this repo it looks good, thanks for sharing! 

There is one problem that I noticed in same network everything works fine but when I complitly change networks it will not work...

I assume it is some problem with RTC config and stun, but I couldn't figure out how to fix that.

Could you check? I put app on heroku for testing: https://test-webrpc.herokuapp.com/

**Comment by Basscord** [comment]
Nice! I checked it out and it's working pretty well! Your assumption about STUN being the issue is correct. There's some places where it can be fixed and some places where it can't.

You can set breakpoints or console.logs here to see what types of connection candidates you receive:
https://github.com/Basscord/webrtc-video-broadcast/blob/master/public/watch.js#L23

And here to see what types of connection candidates you emit:
https://github.com/Basscord/webrtc-video-broadcast/blob/master/public/watch.js#L17

If you emit and receive several candidates, you're gonna connect. If you don't receive many, you probably won't.

You can increase the number of candidates you emit and receive by adding ICE servers here:
https://github.com/Basscord/webrtc-video-broadcast/blob/master/public/index.js#L5

Depending on how far you want to take it, you could deploy a [Coturn docker container](https://hub.docker.com/r/zolochevska/turn-server/) to Heroku, and add it to the ICE servers, which would make connectivity pretty much 100%.

But I've also seen some instances where a device firewall or ISP was blocking the ports, and there was no way to connect that device at all.

Let me know how things go. Thanks!

**Comment by vforv** [comment]
@Basscord, thanks for answer. 

It works for me as well when I using same ISP and Nat. But when I change ISP or use same ISP but diffirent nats it doesn't work.

I updated heroku app added console.log on 17. and 23. to see which candidats I send and receive when using diffirent ISP, I got 2 which send and 3 recived.
Here is the result:
http://dodaj.rs/images/xpvjA.png

I tested your example as well: https://video-chat.basscord.co/[room-name-goes-here], have same problem...

Any idea what can be a problem?

**Comment by vforv** [comment]
@Basscord I fixed it.

Problem was with missing turn server. So I find site where you can register and get free turn server:
http://numb.viagenie.ca/

And added it to line 5.

Thanks!

**Comment by dan-engineering** [comment]
Question:

If I use the turn server from http://numb.viagenie.ca/ that is in canada but I am located somwhere europe. Would that make my connection really bad?

As far as I understand: STUN establishes a direct connection P2P, thus no problem where STUN is located. But TURN establishes a pseudo P2P because data travels via TURN... Did I misunderstood something?

Thanks

**Comment by Basscord** [comment]
Hi @Mcdane,

Your understanding is correct. Your connection will probably be passable, but certainly more latent than a connection on the same continent. Viagenie may or may not be offering a distributed system, which would mean they might have some servers in Europe as well. If that's is not the case, then you might either look into paying for something like Twilio, or deploying [CoTURN](https://www.webrtc-experiment.com/docs/TURN-server-installation-guide.html#coturn) to a server in your region.

Let me know how it goes!
